server:
  port: 8080

spring:
#  profiles:
#    active: local

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  application:
    name: we-go-app

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${RDS_ENDPOINT}:3306/wego?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&cachePrepStmts=true&prepStmtCacheSize=250&prepStmtCacheSqlLimit=2048&useServerPrepStmts=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USER}
    password: ${RDS_PASSWORD}

    hikari:
      pool-name: we-go-dev
      maximum-pool-size: 12
      minimum-idle: 12
      connection-timeout: 5000
      max-lifetime: 1800000
      idle-timeout: 600000
      validation-timeout: 1000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        show_sql: true
        jdbc.time_zone: Asia/Seoul
        generate_statistics: false
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 300
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 2s

      ssl:
        enabled: false

      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 1
          max-wait: 2s


aws:
  s3:
    bucket: we-go-bucket
    region: ap-northeast-2
    public-endpoint: ${S3_ENDPOINT}
    access-key-id: ${S3_ACCESS_KEY_ID}
    secure-access-key: ${S3_SECURE_ACCESS_KEY}

image:
  max-size-bytes: 20971520 # 10MB
  max-width: 2000
  max-height: 2000

  thumb-max-width: 600
  thumb-max-height: 600

jwt:
  secret: ${JWT_SECRET}
  access:
    token:
      expiration: 3600000
  refresh:
    token:
      expiration: 604800000